New auth implementation
ethential/ethcode pull request #153
Opened 2020-09-24 14:59 UTC by Ayanrocks

2020-09-24 21:37 UTC, 0mkara requested changes

2020-09-24 21:37 UTC, 0mkara commented on src/components/App.tsx
> +                  <Button disabled={this.state.appRegistered} onClick={this.handleAppRegister} >Register App</Button>
Do not keep disabled button when the app is authenticated. Show authenticated status in account section.

2020-09-24 21:37 UTC, 0mkara commented on src/components/App.tsx
> +        this.setState({appRegistered: data.registered})
Wrong indentation.

2020-09-29 07:59 UTC, 0mkara approved these changes

2020-09-29 08:21 UTC, Ayanrocks reviewed
LGTM

2020-09-29 08:43 UTC, merged